services:
  - type: worker
    name: ambient-research-summarizer
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    plan: starter
    envVars:
      - key: NEWS_API_KEY
        sync: false
      - key: SLACK_WEBHOOK_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
